root = "."
tmp_dir = ".air/tmp"

[build]
  cmd = "go build -o ./.air/tmp/386gpt ."
  entrypoint = ["./.air/tmp/386gpt"]
  include_ext = ["go"]
  exclude_dir = [".air", "data"]
  delay = 250
  stop_on_error = true
  send_interrupt = true
  kill_delay = "500ms"

[log]
  time = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true
